export const XEM_CHI_TIET = 'XEM_CHI_TIET'
export const THEM_GIO_HANG = 'THEM_GIO_HANG'
export const TANG_SO_LUONG = 'TANG_SO_LUONG'
export const GIAM_SO_LUONG = 'GIAM_SO_LUONG'
export const TINH_TONG_TIEN = 'TINH_TONG_TIEN'
export const XOA_GIO_HANG = 'XOA_GIO_HANG'